### ISSUE TITLE
Buggy handling of non-json errors from the Pipl API

### ISSUE THREAD

**Issue by salty-horse** [piplcom/piplapis-python#24]
The code for [`send()`](https://github.com/piplcom/piplapis-python/blob/b8bf652435922b93a248448b3e2b18c56c03a2a6/piplapis/search.py#L356) incorrectly assumes that all errors from the Pipl API are JSON, and attempts to decode them, which leads to a further exception, and a verbose exception chain.

Due to this, the caller doesn't receive an exception, and the `SearchAPIResponse` object is returned as if nothing bad happened, with critical fields such as `http_status_code` set to `None`.

It should check if the response is in JSON before attempting to decode it.

Example exception:
```
ERROR:root:HTTPError: Error fetching data from Pipl
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/piplapis/search.py", line 341, in send
    exception = SearchAPIError.from_json(json_error.decode())
  File "/usr/local/lib/python3.6/site-packages/piplapis/data/utils.py", line 127, in from_json
    d = json.loads(json_str)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/syncme/integrations/pipl/search.py", line 440, in __query_pipl
    response = request.send()
  File "/usr/local/lib/python3.6/site-packages/piplapis/search.py", line 345, in send
    raise e
  File "/usr/local/lib/python3.6/site-packages/piplapis/search.py", line 331, in send
    response = urllib2.urlopen(request)
  File "/usr/local/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway
```

**Comment by 14672** [comment]
> 
![Uploading 156B4231-F14A-4318-97F2-B057200AEC2A.png…]()

**Comment by 14672** [comment]
#23
